import { readFileSync, writeFileSync } from 'node:fs';
import { basename, resolve } from 'node:path';

const input = resolve(process.argv[2] ?? 'assets/MAPS/Map.ldtk');
const output = resolve(process.argv[3] ?? 'assets/Code/Infrastructure/GeneratedLevels.ts');
const project = JSON.parse(readFileSync(input, 'utf8'));

const entityTokens = {
    END: 'E...',
    WALL: '####',
    ENEMY_VOID: 'XXXX',
    PLAYER: 'P...',
    DOT: 'o...',
    COIN: 'C...',
    BOOTST_COINS: 'G...',
    BOOST_FREEZE: 'I...',
    ENEMY_FISH: '.F..',
    BOOST_MAGNER: 'M...',
    BOOST_MAGNET: 'M...',
    SPIKE: '^^^^',
};
const directions = { North: 0, South: 1, West: 2, East: 3, UP: 0, DOWN: 1, LEFT: 2, RIGHT: 3 };
const deltas = [[0, -1], [0, 1], [-1, 0], [1, 0]];
const directionNames = ['North', 'South', 'West', 'East'];

function field(entity, name) {
    return entity.fieldInstances?.find(value => value.__identifier === name)?.__value;
}

function directionalToken(symbol, direction) {
    const token = ['.', '.', '.', '.'];
    token[directions[direction]] = symbol;
    return token.join('');
}

function enumName(identifier, index) {
    const safe = identifier.replace(/\W/g, '_').replace(/^(\d)/, '_$1');
    return safe || `Level_${index}`;
}

function convertLevel(level) {
    const layer = level.layerInstances?.find(value => value.__type === 'Entities');
    if (!layer) throw new Error(`${level.identifier}: missing Entities layer`);
    const width = layer.__cWid;
    const height = layer.__cHei;
    const entities = layer.entityInstances ?? [];
    const byCell = new Map();
    for (const entity of entities) {
        const key = entity.__grid.join(',');
        if (byCell.has(key)) throw new Error(`${level.identifier}: multiple entities at [${key}]`);
        byCell.set(key, entity);
    }

    const isSolid = (column, row) => {
        if (column < 0 || row < 0 || column >= width || row >= height) return true;
        const id = byCell.get(`${column},${row}`)?.__identifier;
        return id === 'WALL' || id === 'SPIKE' || id === 'ENEMY_VOID' || id === 'ENEMY_CANNON';
    };
    const inferDirection = entity => {
        const [column, row] = entity.__grid;
        const open = deltas.flatMap(([dx, dy], index) => isSolid(column + dx, row + dy) ? [] : [index]);
        if (open.length !== 1) throw new Error(`${level.identifier}: ${entity.__identifier} at [${column},${row}] needs exactly one open neighbor, found ${open.length}`);
        return directionNames[open[0]];
    };

    const players = entities.filter(entity => entity.__identifier === 'PLAYER');
    const ends = entities.filter(entity => entity.__identifier === 'END');
    if (players.length !== 1) throw new Error(`${level.identifier}: expected exactly one PLAYER, found ${players.length}`);
    if (ends.length !== 1) throw new Error(`${level.identifier}: expected exactly one END, found ${ends.length}`);
    if (ends[0].__grid[1] !== 0) throw new Error(`${level.identifier}: END must be on the top row`);

    const rows = Array.from({ length: height }, () => Array(width).fill('....'));
    for (const entity of entities) {
        const [column, row] = entity.__grid;
        let token = entityTokens[entity.__identifier];
        if (entity.__identifier === 'ENEMY_CANNON') {
            const direction = field(entity, 'Direction') ?? inferDirection(entity);
            token = directionalToken('T', direction);
        } else if (entity.__identifier === 'ENEMY_BAT') {
            const orientation = field(entity, 'Move_Orientation');
            if (orientation !== 'Horizontal' && orientation !== 'Vertical') throw new Error(`${level.identifier}: ENEMY_BAT at [${column},${row}] needs Move_Orientation`);
            token = directionalToken('B', orientation === 'Horizontal' ? 'East' : 'South');
        } else if (entity.__identifier === 'PORTAL') {
            const id = field(entity, 'Id');
            if (!Number.isInteger(id) || id < 0 || id > 9) throw new Error(`${level.identifier}: PORTAL at [${column},${row}] needs integer Id 0-9`);
            token = `V00${id}`;
        } else if (entity.__identifier === 'TRAMPLINE') {
            token = directionalToken('J', field(entity, 'Direction') ?? inferDirection(entity));
        }
        if (!token) throw new Error(`${level.identifier}: unsupported entity ${entity.__identifier} at [${column},${row}]`);
        rows[row][column] = token;
    }
    return rows;
}

const levels = project.levels.map(convertLevel);
const enumEntries = project.levels.map((level, index) => `    ${enumName(level.identifier, index)} = ${index},`).join('\n');
const levelEntries = levels.map((rows, index) => `    // ${project.levels[index].identifier}\n    [\n${rows.map(row => `        [${row.map(cell => `'${cell}'`).join(', ')}],`).join('\n')}\n    ],`).join('\n');
const source = `// Generated by tools/convert-ldtk.mjs from ${basename(input)}. Do not edit.\nimport type { LevelConfig } from './LevelLibrary';\n\nexport enum LevelId {\n${enumEntries}\n}\n\nexport const LDTK_LEVELS: readonly LevelConfig[] = [\n${levelEntries}\n];\n`;
writeFileSync(output, source);
console.log(`Converted ${levels.length} LDtk levels -> ${output}`);
